---
- name: DevOps Project
  hosts: myserver
  become: yes

  tasks:
  - name: Install required packages
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - epel-release
      - python3-pip

  - name: Install Docker on second machine
    shell: >
      curl https://get.docker.com | bash && \
      systemctl start docker && \
      systemctl enable docker
    become: yes
    vars:
      ansible_ssh_host: 192.168.111.12


  - name: Start and enable Docker service
    systemd:
      name: docker
      state: started
      enabled: true

  - name: Install requests module
    pip:
      name: requests
      state: present
    become: yes
    vars:
      ansible_python_interpreter: /usr/bin/python3

  - name: Install Docker SDK for Python
    pip:
      name: docker
      executable: pip3
    become: yes 

  - name: Pull Jenkins container
    docker_container:
      name: jenkins
      image: jenkins/jenkins:lts
      state: started
      pull: true
      published_ports:
        - "8080:8080"
      container_default_behavior: "no_defaults" 
    become: yes
    vars:
      ansible_ssh_host: 192.168.111.12
      ansible_python_interpreter: /usr/bin/python3

  - name: Pull SonarQube container
    docker_container:
      name: sonarqube
      image: sonarqube
      state: started
      pull: true
      published_ports:
        - "9000:9000"
      container_default_behavior: "no_defaults"
    become: yes
    vars:
      ansible_ssh_host: 192.168.111.12
      ansible_python_interpreter: /usr/bin/python3

  - name: Pull Nginx container
    docker_container:
      name: nginx
      image: nginx
      state: started
      pull: true
      published_ports:
        - "80:80"
      container_default_behavior: "no_defaults"
    become: yes
    vars:
      ansible_ssh_host: 192.168.111.12
      ansible_python_interpreter: /usr/bin/python3

  - name: Copy index.html to target node
    copy:
      src: /root/PROJECT/fiipractic-devops-project/index.html
      dest: /tmp/index.html
    become: yes
    vars:
      ansible_ssh_host: 192.168.111.12

  - name: Copy index.html to Nginx container
    shell: docker cp /tmp/index.html nginx:/usr/share/nginx/html/
    become: yes
    vars:
      ansible_ssh_host: 192.168.111.12

